### PR TITLE
fix path in Quick start example

### PR DESCRIPTION
**Pull request by myTerminal**
This change is [Reviewable](https://reviewable.io/reviews/eight04/inline-js/1)

### CODE REVIEW

**Comment by eight04** [comment]
Oops, I didn't notice that, and there are even more errors.

Would you mind to fix the sample code under "Use .inline.js" section?
```diff
-		expand: (file, arg1, arg2, ...args) {
+		expand(file, arg1, arg2, ...args) {
-		transform: (content, arg1, arg2, ...args) {
+		transform(content, arg1, arg2, ...args) {
```

**Comment by myTerminal** [comment]
Done :)

**Comment by myTerminal** [comment]
Could you merge this one?

**Comment by myTerminal** [comment]
Thanks :)

**Pull request merged**
